# Generated by Django 2.2 on 2019-12-04 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='image',
        ),
    ]
